class Es7234e:
    def __init__(self, i2c): ...
    def deinit(self) -> None: ...
    def open(self) -> bool: ...
    def adc_enable(self, enable: bool) -> bool: ...
    def set_gain(self, db: float) -> bool: ...