class I2SSpeaker:
    def __init__(self): ...
    def deinit(self) -> None: ...
    def open(self) -> bool: ...
    def play_sys_music(self, filename: str) -> None: ...
    def play_tf_music(self, filename: str) -> None: ...
    def play_wav(self, filename: str) -> None: ...