class I2SMic:
    def __init__(self, i2c): ...
    def deinit(self) -> None: ...
    def open(self) -> bool: ...
    def record_sys(self, filename: str, duration=5) -> bool: ...
    def record_tf(self, filename: str, duration=5) -> bool: ...
