ANGRY:bytes  # 生气
BORED:bytes  # 无聊
CONFUSED:bytes  # 困惑
HAPPY:bytes  # 开心
HEART:bytes  # 心形
PAPER:bytes  # 布(剪刀/石头/布)
ROCK:bytes  # 石头(剪刀/石头/布)
SAD:bytes  # 悲伤表情的字节数据
SCISSORS:bytes  # 剪刀(剪刀/石头/布)
SILLY:bytes  # 傻气
SLEEP:bytes  # 睡觉
SMALL_HEART:bytes  # 小心形
SMALL_PAPER:bytes  # 小布(剪刀/石头/布)
SMALL_ROCK:bytes  # 小石头(剪刀/石头/布)
SMALL_SCISSORS:bytes  # 小剪刀(剪刀/石头/布)
SMILE:bytes  # 微笑
SURPRISE:bytes  # 惊喜
WONDERFUL:bytes  # 精彩
