# This file is autogenerated for soft_reset MicroPython C module
from typing import Callable, Any

def on_reset(func: Callable[[], Any]) -> None:
    '''
    函数说明
    参数:
        func (Callable[[], Any]): 软重启时调用的回调函数
    返回:
        None: 无返回值
    '''
    ...

def remove(func: Callable[[], Any]) -> None:
    '''
    函数说明
    参数:
        func (Callable[[], Any]): 要移除的回调函数
    返回:
        None: 无返回值
    '''
    ... 